version: "3.9"

services:
  psql_local:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: psqludemy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --version"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - psql_local_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - psql_local

volumes:
  psql_local_data:
  pgadmin_data: